"use client";
import { useState } from 'react';
type Data = { [key: string]: any }; type Chunk = { text: string; beat: string; important?: boolean };
const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';
const LESSON: Chunk[] = [
{text:'Today we are asking a deceptively simple question: how does a neuron send a message?',beat:'Orient: one question, one thread.',important:true},
{text:'A neuron keeps its resting voltage by moving charged particles across its membrane.',beat:'Resting potential is the baseline.'},
{text:'A small signal nudges the membrane. If it reaches threshold, the neuron commits to a full action potential.',beat:'Important moment: threshold is all-or-nothing.',important:true},
{text:'Sodium channels open first, sodium rushes in, and the membrane rapidly depolarizes.',beat:'The rising phase is the electrical spark.'},
{text:'Sodium channels inactivate while potassium channels open, pushing the voltage back down.',beat:'Repolarization restores the signal.'},
{text:'For a brief refractory period, the neuron cannot immediately fire again; this keeps the message moving forward.',beat:'The pause prevents backwards firing.',important:true},
{text:'The action potential travels down the axon without fading because each segment regenerates the signal.',beat:'A chain of fresh sparks, not a dying wave.'},
{text:'Myelin acts like insulation. Gaps called nodes let the signal jump, making conduction much faster.',beat:'Saltatory conduction: jump from node to node.',important:true},
{text:'At the axon terminal, calcium entry triggers neurotransmitter release across the synapse.',beat:'Electrical message becomes chemical message.'},
{text:'The receiving neuron sums its inputs. If the total crosses threshold, the cycle begins again: neurons fire, connect, and learn.',beat:'Takeaway: tiny inputs become a decisive message.',important:true},
];
const QUESTIONS = ['What is the main idea?','Explain threshold simply','What should I remember?'];
async function post(path: string, body: Data): Promise<Data> { const response = await fetch(`${API}${path}`, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(body)}); const data = await response.json(); if (!response.ok || data.ok === false) throw new Error(data.error || 'Lecture request failed'); return data; }
export default function LectureCopilotPage() {
 const [draft,setDraft]=useState(''),[transcript,setTranscript]=useState(''),[caption,setCaption]=useState('Waiting for the next idea…'),[notes,setNotes]=useState<Data>({key_points:[],terms:[],action_items:[]}),[question,setQuestion]=useState(''),[answer,setAnswer]=useState(''),[index,setIndex]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''); const chunk=LESSON[index];
 async function send(text:string) { if(!text.trim()) return; setBusy(true);setError(''); try { const ingested=await post('/api/lecture/ingest',{text_chunk:text,timestamp:new Date().toISOString()}); const next=ingested.data.transcript; const [cap,note]=await Promise.all([post('/api/lecture/caption',{transcript:next}),post('/api/lecture/notes',{transcript:next})]); setTranscript(next);setCaption(cap.data.caption);setNotes(note.data);setDraft(''); } catch(e) {setError(e instanceof Error?e.message:'Could not reach the local API');} finally {setBusy(false);} }
 async function explain(value=question) { if(!value.trim()||!transcript)return;setBusy(true);setError('');try {const result=await post('/api/lecture/explain',{question:value,lecture_context:transcript});setQuestion(value);setAnswer(result.data.answer);}catch(e){setError(e instanceof Error?e.message:'Could not explain that yet');}finally{setBusy(false);} }
 return <main style={s.shell}><header style={s.header}><div><div style={s.brand}><b>C</b> CLASS<span>BRIDGE</span></div><small>LECTURE COPILOT / DEMO</small></div><a href='/' style={s.back}>← Neuro view</a></header><section style={s.intro}><div><small style={s.label}>ACCESSIBLE LECTURE SUPPORT</small><h1>Keep the thread.<br/><em>One clear idea at a time.</em></h1><p style={s.muted}>A realistic ten-beat lesson on how neurons fire, with important moments visible for captions, notes, and click-to-explain.</p></div><div style={s.status}>● LOCAL DEMO<br/><strong>HEURISTIC FALLBACK READY</strong></div></section><section style={s.grid}><article style={s.panel}><small style={s.label}>01 / TEACHER INPUT</small><h2>Speak or step through</h2><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder='The teacher is explaining…' style={s.textarea}/><div style={s.row}><button onClick={()=>void send(draft)} disabled={busy||!draft.trim()} style={s.primary}>Send chunk ↗</button><button onClick={()=>{void send(chunk.text);setIndex(Math.min(index+1,9));}} disabled={busy} style={s.secondary}>Play beat {index+1}/10</button></div><div style={s.sample}><small style={s.label}>CURRENT LESSON BEAT</small><p>{chunk.text}</p><strong>{chunk.important?'★ ':''}{chunk.beat}</strong></div></article><article style={s.panel}><small style={s.label}>02 / LIVE OUTPUT</small><h2>Smart captions <span style={s.live}>● LIVE</span></h2><div style={s.caption}><strong>{caption}</strong><small>Fillers removed · short, engaging sentences</small></div><small style={s.label}>ACCUMULATED TRANSCRIPT</small><p style={s.transcript}>{transcript||'Your lesson transcript will appear here.'}</p></article><article style={s.panel}><small style={s.label}>03 / AUTO-NOTES</small><h2>Study trail</h2><Notes title='KEY MOMENTS' items={notes.key_points||[]} empty='Send a chunk to build key moments.'/><Notes title='TERMS' items={notes.terms||[]} empty='Important terms will surface here.'/><Notes title='ACTION ITEMS' items={notes.action_items||[]} empty='No action items yet.'/></article><article style={s.panel}><small style={s.label}>04 / ASK THE LECTURE</small><h2>Explain a concept</h2><div style={s.questions}>{QUESTIONS.map(item=><button key={item} onClick={()=>void explain(item)} disabled={!transcript||busy} style={s.question}>{item} ↗</button>)}</div><div style={s.row}><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void explain();}} placeholder='Ask your own question' style={s.input}/><button onClick={()=>void explain()} disabled={!question.trim()||!transcript||busy} style={s.primary}>Ask</button></div>{answer&&<div style={s.answer}><small style={s.label}>PLAIN-LANGUAGE ANSWER</small><p>{answer}</p></div>}</article></section>{error&&<p style={s.error}>{error}</p>}<footer style={s.footer}><span>CLASSBRIDGE / LECTURE COPILOT</span><span>Works without an LLM · deterministic demo fallback</span></footer></main>;
}
function Notes({title,items,empty}:{title:string;items:string[];empty:string}) { return <div style={s.notes}><small style={s.label}>{title}</small>{items.length?<ul>{items.map(item=><li key={item}>{item}</li>)}</ul>:<p style={s.empty}>{empty}</p>}</div>; }
const s:{[key:string]:any}={shell:{maxWidth:1180,margin:'0 auto',padding:'24px 24px 40px',color:'#eff8f7',minHeight:'100vh',fontFamily:'Manrope,system-ui,sans-serif'},header:{display:'flex',justifyContent:'space-between',alignItems:'center',borderBottom:'1px solid #29423e',paddingBottom:20},brand:{fontWeight:800,letterSpacing:'.12em',fontSize:14},back:{color:'#9df4c0',textDecoration:'none',fontSize:12},intro:{display:'flex',justifyContent:'space-between',alignItems:'end',gap:24,padding:'58px 0 34px'},label:{color:'#9df4c0',fontSize:10,letterSpacing:'.13em'},muted:{maxWidth:590,color:'#91a59d',lineHeight:1.6},status:{border:'1px solid #29423e',borderRadius:10,padding:'12px 14px',color:'#9df4c0',fontSize:10,letterSpacing:'.12em',lineHeight:1.8},grid:{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:16},panel:{background:'linear-gradient(145deg,#13251f,#0d1915)',border:'1px solid #29423e',borderRadius:16,padding:22,minHeight:240},textarea:{width:'100%',minHeight:120,resize:'vertical',background:'#08120f',color:'#eff8f7',border:'1px solid #29423e',borderRadius:10,padding:14,font:'inherit',boxSizing:'border-box'},row:{display:'flex',gap:8,marginTop:12},primary:{background:'#9df4c0',color:'#08120f',border:0,borderRadius:7,padding:'10px 14px',fontWeight:700,cursor:'pointer'},secondary:{background:'transparent',color:'#eff8f7',border:'1px solid #426356',borderRadius:7,padding:'10px 14px',cursor:'pointer'},sample:{marginTop:22,color:'#91a59d',fontSize:12,lineHeight:1.5},caption:{background:'#08120f',borderLeft:'3px solid #9df4c0',padding:'22px 18px',borderRadius:8,margin:'18px 0 20px'},live:{color:'#9df4c0',fontSize:10},transcript:{color:'#91a59d',fontSize:13,lineHeight:1.6},notes:{borderTop:'1px solid #29423e',paddingTop:13,marginTop:12},empty:{color:'#647b72',fontSize:12},questions:{display:'grid',gap:8,margin:'18px 0 12px'},question:{textAlign:'left',background:'#172f27',border:'1px solid #355149',borderRadius:8,color:'#eff8f7',padding:'10px 12px',cursor:'pointer'},input:{flex:1,minWidth:0,background:'#08120f',color:'#eff8f7',border:'1px solid #29423e',borderRadius:7,padding:'10px 12px',font:'inherit'},answer:{marginTop:20,borderTop:'1px solid #29423e',paddingTop:16,lineHeight:1.6},error:{color:'#ff9b88',border:'1px solid #6a3b32',padding:12,borderRadius:8},footer:{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap',marginTop:28,paddingTop:18,borderTop:'1px solid #29423e',color:'#91a59d',fontSize:10,letterSpacing:'.1em'}};
