import {useCallback,useEffect,useRef,useState,type RefObject} from 'react';
import {BlinkDetector,type BlinkState} from './blinkDetector';
import {applyCalibration,CALIBRATION_POINTS,fitCalibration,type CalibrationSample} from './calibration';
import {EmaSmoother,type Point} from './emaSmooth';
import {GazeEstimator} from './gazeEstimator';
export type GazeStatus='idle'|'loading'|'tracking'|'calibrating'|'error';
export type GazeCursor=Point&{visible:boolean};
export function useGaze(videoRef:RefObject<HTMLVideoElement|null>){const[cameraEnabled,setCameraEnabled]=useState(false),[status,setStatus]=useState<GazeStatus>('idle'),[error,setError]=useState('');const[cursor,setCursor]=useState<GazeCursor>({x:.5,y:.5,visible:false}),[calibrationStep,setCalibrationStep]=useState(-1),[calibrated,setCalibrated]=useState(false),[blink,setBlink]=useState<BlinkState>({leftEar:1,rightEar:1,ear:1,isClosed:false,blinked:false}),[calibrationError,setCalibrationError]=useState<number|null>(null);const step=useRef(-1),started=useRef(0),samples=useRef<CalibrationSample[]>([]),model=useRef<ReturnType<typeof fitCalibration>|null>(null),task=useRef<GazeEstimator|null>(null),stream=useRef<MediaStream|null>(null),frame=useRef<number|null>(null),smooth=useRef(new EmaSmoother()),detector=useRef(new BlinkDetector());
const startCalibration=useCallback(()=>{if(!cameraEnabled||status==='loading'){setError('Turn on the camera before calibrating.');return;}samples.current=[];model.current=null;smooth.current.reset();step.current=0;started.current=performance.now();setCalibrationStep(0);setCalibrated(false);setCalibrationError(null);setError('');setStatus('calibrating');},[cameraEnabled,status]);
useEffect(()=>{if(!cameraEnabled){if(frame.current!==null)cancelAnimationFrame(frame.current);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;task.current?.close();task.current=null;step.current=-1;setCalibrationStep(-1);setCursor(p=>({...p,visible:false}));setStatus('idle');return;}let cancelled=false;async function boot(){setStatus('loading');try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('This browser does not expose camera access.');const[media,tracker]=await Promise.all([navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false}),GazeEstimator.create()]);if(cancelled){media.getTracks().forEach(t=>t.stop());tracker.close();return;}stream.current=media;task.current=tracker;const video=videoRef.current;if(!video)throw new Error('Camera preview is not ready.');video.srcObject=media;video.muted=true;await video.play();setStatus('tracking');const loop=()=>{if(cancelled||!task.current||!videoRef.current||videoRef.current.readyState<2)return;try{const result=task.current.estimate(videoRef.current);if(!result){setCursor(p=>({...p,visible:false}));detector.current.reset();}else{const raw=smooth.current.update(result.raw),point=model.current?applyCalibration(model.current,raw):raw;setCursor({...point,visible:true});setBlink(detector.current.update(result.landmarks));if(step.current>=0){samples.current.push({target:CALIBRATION_POINTS[step.current],gaze:raw});if(performance.now()-started.current>=1200&&samples.current.length>=14){if(step.current===4){const fitted=fitCalibration(samples.current);model.current=fitted;setCalibrationError(fitted.error);setCalibrated(true);step.current=-1;setCalibrationStep(-1);setStatus('tracking');}else{step.current++;started.current=performance.now();samples.current=[];setCalibrationStep(step.current);smooth.current.reset();}}}}}catch(e){setError(e instanceof Error?e.message:'Gaze tracking stopped.');setStatus('error');}frame.current=requestAnimationFrame(loop);};frame.current=requestAnimationFrame(loop);}catch(e){setError(e instanceof Error?e.message:'Unable to start local gaze tracking.');setStatus('error');setCameraEnabled(false);}}void boot();return()=>{cancelled=true;if(frame.current!==null)cancelAnimationFrame(frame.current);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;task.current?.close();task.current=null;};},[cameraEnabled,videoRef]);return{cameraEnabled,toggleCamera:useCallback(()=>setCameraEnabled(v=>!v),[]),status,error,cursor,blink,calibrated,calibrationStep,calibrationTargets:CALIBRATION_POINTS,startCalibration,calibrationError};}
